#! /bin/sh
#--------------------------------------------------------# Part - 0
xmodmap .xmodmap-sid & # remove this 

#--------------------------------------------------------# Part - 1
#bspc monitor -d Home Web Work Files Mails Misc          # Monitor Names
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d www term code file social

#--------------------------------------------------------# Part - 2
bspc config border_width         2
bspc config window_gap           3

#--------------------------------------------------------# Part - 3
# bspc config top_padding 31                             # Bspwm Gaps
# bspc config bottom_padding 0

#--------------------------------------------------------# Part - 4
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

#--------------------------------------------------------# Part - 5
# . "${HOME}/.cache/wal/colors.sh"                       # Gets Pywall Colors
# bspc config normal_border_color "$color2"
# bspc config active_border_color "$color14"
# bspc config focused_border_color "$color15"
# bspc config presel_feedback_color "$color1"

# #---------------------------------------------------------
bspc config focused_border_color        "#FFFFFF"       # Border Color
bspc config normal_border_color         "#151515"
bspc config active_border_color         "#FFF8E5"

#--------------------------------------------------------# Part - 6
# Send Specific Apps to specific Desktop 
# Command To check window name -> xprop | grep WM_CLASS
bspc rule -a firefox desktop=^10                         # Chromium
bspc rule -a Chromium desktop=^2                         # Chromium
bspc rule --add librewolf desktop=^10                    # Librewolf
bspc rule --add Microsoft-edge desktop=^2                # Microsoft-edge
bspc rule --add code-oss desktop=^3 state=focused        # Vs Code
bspc rule --add Subl desktop=^3                          # Sublime Text
bspc rule --add thunar desktop=^3                        # Thunar

#--------------------------------------------------------# Part - 7
bspc rule --add stacer state=floating border=off         # Stacer
bspc rule --add Windscribe2 state=floating border=off    # Windscribe Vpn
bspc rule --add xdman-Main state=floating border=off hidden=on    # XDM Download Manager
bspc rule --add copyq state=tiled border=off             # CopyQ               
bspc rule --add Ulauncher state=floating border=off      # Ulauncher
bspc rule --add 'zoom ' state=floating border=off        # Zoom
bspc rule --add GLava state=floating border=off          # Emoji Keybord
bspc rule --add MEGAsync state=floating border=off       # MEGAsync
bspc rule --add Emojione-picker state=floating border=off # Emojione-picker              
bspc rule --add flameshot state=floating border=off       #flameshot
bspc rule --add flameshot state=floating border=off       #flameshot

# 7 > media
declare -a media=(mpv Music MPlayer Lxmusic Inkscape Gimp-2.10 obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

# bspc rule -a TelegramDesktop state=fullscreen layer=above
# bspc rule -a Spotify state=floating rectangle=500x500+500+500 sticky=off
bspc rule -a Pavucontrol rectangle 1000x600+50+50 state=floating sticky=off border=off

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

#--------------------------------------------------------# Part - 8
# Autostart Necessary applications - 1 
# feh --randomize --bg-fill /$HOME/Pictures/Wallpapers/ &                    # fetch random wallpapers
# nitrogen --restore                                                         # restore previous nitrogen wallpaper
~/.config/polybar/scripts/pywal.sh --theme &                                         # set a new wallpaper with similar theme
xrdb merge ~/.Xresources &                                                   # --
bash .config/polybar/launch.sh &                                             # launches polybar
~/.config/bspwm/scripts/get-window-aspect-ratio.sh                           # resize the focused window to an aspect ratio

# Auto suspend when not online [ paru -Sy --noconfirm --needed xidlehook ] - (Better option is to add to .xinitrc)
# 300s - 5m / 900s - 15m / 1800s - 30m / 3600s - 1h / 86400s -24h
# xidlehook --not-when-audio --not-when-fullscreen --timer 600 'systemctl suspend' 'betterlockscreen -l --text "Error 404:Desktop Crashed"'  &  

# Basic Wallpaer / Themes / Picom / Keybindings
picom &                                                                     # Picom with transparency 
pgrep -x sxhkd >/dev/null || sxhkd &                                        # Restarts Sxhkd

# Auto Start Applications
# nm-applet &
# pamac-tray &
# xfce4-power-manager &
# numlockx on &
# /usr/bin/dunst &

# Cursor Theme
xsetroot -PearDarkCursors left_ptr &
xsetroot -cursor_name left_ptr &

# xsetroot -cursor_name left_ptr
# Enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
