#! /bin/sh

xmodmap .xmodmap-sid & # remove this 

#bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           2

#Bspwm Gaps
bspc config top_padding 30
bspc config bottom_padding 0

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#43a047"
bspc config normal_border_color         "#ffffff"
bspc config active_border_color         "#f4dd"



# bspc rule -a Gimp desktop='^2' follow=on state=tiled


#------------------------------------------------------------------------------------------------------------------
# autostart up applications 
# feh --randomize --bg-fill /$HOME/Pictures/Wallpapers/ & #fetch random wallpapers
# nitrogen --restore
~/.config/polybar/cuts/scripts/pywal.sh ~/Pic/ &
xrdb merge ~/.Xresources &
bash ~/.config/polybar/launch.sh --shapes &

# Auto suspend when not online [ paru -Sy --noconfirm --needed xidlehook ]
# 300s - 5m / 900s - 15m / 1800s - 30m / 3600s - 1h / 86400s -24h

xidlehook --not-when-audio --not-when-fullscreen --timer 600 'systemctl suspend' 'betterlockscreen -l --text "Error 404:Desktop Crashed"'  &  


# Basic Wallpaer / Themes / Picom / Keybindings
# ~/.config/bspwm/scripts/changewal.sh &
picom & 
pgrep -x sxhkd >/dev/null || sxhkd &

lxappearance &
killall lxappearance

# Auto Start Applications
# nm-applet &
# pamac-tray &
# xfce4-power-manager &
# numlockx on &
# /usr/bin/dunst &


#blueberry-tray &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/xfce4/notifyd/xfce4-notifyd &

# xdman &
# ulauncher &
# megasync &
# conky &
# aw-qt & 
# xfce4-clipman &
# redshift &
