#! /bin/sh
#--------------------------------------------------------# Part - 0
xmodmap .xmodmap-sid & # remove this 
#--------------------------------------------------------# Part - 1
#bspc monitor -d Home Web Work Files Mails Misc          # Monitor Names
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d www term code file social
#--------------------------------------------------------# Part - 2
bspc config border_width         2
bspc config window_gap           3
#--------------------------------------------------------# Part - 3
bspc config top_padding 31                               # Bspwm Gaps
bspc config bottom_padding 0
#--------------------------------------------------------# Part - 4
bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
#--------------------------------------------------------# Part - 5
bspc config focused_border_color        "#e53935"        # Border Color
bspc config normal_border_color         "#3D0000"
bspc config active_border_color         "#e53935"
#--------------------------------------------------------# Part - 6
# Send Specific Apps to specific Desktop 
# To check window name - xprop | grep WM_CLASS
bspc rule -a Chromium desktop=^2                         # Chromium
bspc rule --add librewolf desktop=^10                    # Librewolf
bspc rule --add Microsoft-edge desktop=^3                # Microsoft-edge
bspc rule --add code-oss desktop=^3 state=focused        # Vs Code
bspc rule --add Subl desktop=^3                          # Sublime Text
bspc rule --add thunar desktop=^3                        # Thunar

#bspc rule --add code-oss desktop=^3 
#bspc rule --add code-oss desktop=^3 
#bspc rule --add Zathura state=tiled
#--------------------------------------------------------# Part - 7
bspc rule --add stacer state=floating border=off         # Stacer
bspc rule --add Windscribe2 state=floating border=off    # Windscribe Vpn
bspc rule --add xdman-Main state=floating border=off     # XDM Download Manager
bspc rule --add copyq state=tiled border=off             # CopyQ               
bspc rule --add Ulauncher state=floating border=off      # Ulauncher
bspc rule --add 'zoom ' state=floating border=off        # Zoom
bspc rule --add Com.github.cassidyjames.ideogram state=floating border=off # Emoji Keybord
bspc rule --add MEGAsync state=floating border=off       # MEGAsync
#--------------------------------------------------------# Part - 8
# Autostart Necessary applications - 1 
# feh --randomize --bg-fill /$HOME/Pictures/Wallpapers/ &                    # fetch random wallpapers
nitrogen --restore                                                           # restore previous nitrogen wallpaper
# ~/.config/polybar/cuts/scripts/pywal.sh ~/Pic/ &                           # set a new wallpaper with similar theme
xrdb merge ~/.Xresources &                                                   # --
bash ~/.config/polybar/launch.sh --forest &                                  # Launch simple polybar - 1

# Auto suspend when not online [ paru -Sy --noconfirm --needed xidlehook ]
# 300s - 5m / 900s - 15m / 1800s - 30m / 3600s - 1h / 86400s -24h
xidlehook --not-when-audio --not-when-fullscreen --timer 600 'systemctl suspend' 'betterlockscreen -l --text "Error 404:Desktop Crashed"'  &  

# Basic Wallpaer / Themes / Picom / Keybindings
# ~/.config/bspwm/scripts/changewal.sh &
picom & 
pgrep -x sxhkd >/dev/null || sxhkd &
lxappearance &
killall lxappearance

# Auto Start Applications
# nm-applet &
# pamac-tray &
# xfce4-power-manager &
# numlockx on &
# /usr/bin/dunst &

#blueberry-tray &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/xfce4/notifyd/xfce4-notifyd &

# xdman &
# ulauncher &
# megasync &
# conky &
# aw-qt & 
# xfce4-clipman &
# redshift &
