#! /bin/sh

xmodmap .xmodmap-sid & # remove this 

#bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#000000"
bspc config active_border_color         "#073642"



#------------------------------------------------------------------------------------------------------------------
# autostart up applications 
# feh --randomize --bg-fill /$HOME/Pictures/Wallpapers/ & #fetch random wallpapers
nitrogen --restore
xrdb merge ~/.Xresources &
bash ~/.config/polybar/launch.sh --cuts &

# Auto suspend when not online [ paru -Sy --noconfirm --needed xidlehook ]
# 300s - 5m / 900s - 15m / 1800s - 30m / 3600s - 1h / 86400s -24h

xidlehook --not-when-audio --not-when-fullscreen --timer 600 'betterlockscreen -l --text "Error 404:Desktop Crashed"' 'systemctl suspend' &  


# Basic Wallpaer / Themes / Picom / Keybindings
# ~/.config/bspwm/scripts/changewal.sh &
picom & 
pgrep -x sxhkd >/dev/null || sxhkd &

# Auto Start Applications
nm-applet &
pamac-tray &
xfce4-power-manager &
numlockx on &
/usr/bin/dunst &
#blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &

# xdman &
# ulauncher &
# megasync &
# conky &
# aw-qt & 
# xfce4-clipman &
# redshift &
